# SPDX-FileCopyrightText: 2025 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0

[settings]
experimental = true
paranoid = true

[env]
HTTP_PROXY = "{{ get_env(name='HTTP_PROXY', default='') }}"
HTTPS_PROXY = "{{ get_env(name='HTTPS_PROXY', default='') }}"
NO_PROXY = "{{ get_env(name='NO_PROXY', default='') }}"
http_proxy = "{{ get_env(name='http_proxy', default='') }}"
https_proxy = "{{ get_env(name='https_proxy', default='') }}"
no_proxy = "{{ get_env(name='no_proxy', default='') }}"
PIP_INDEX_URL = "{{ get_env(name='PIP_INDEX_URL', default='') }}"

[tools]
node = "22"
"aqua:casey/just" = "1.43.0"
"aqua:rhysd/actionlint" = "v1.7.8"
"aqua:siderolabs/conform" = "v0.1.0-alpha.30"
"aqua:zricethezav/gitleaks" = "v8.29.1"
"ubi:rvben/rumdl" = "v0.0.173"
"aqua:koalaman/shellcheck" = "v0.11.0"
"aqua:mvdan/sh" = "v3.12.0"
"aqua:google/yamlfmt" = "v0.20.0"
"pipx:reuse" = "6.2.0"
