# SPDX-FileCopyrightText: 2024 Digg - The Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0

name: wallet-verifier-test-web

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  commitlint:
    uses: diggsweden/.github/.github/workflows/commit-lint.yml@main     
  dependencyreviewlint:
    uses: diggsweden/.github/.github/workflows/dependency-review.yml@main
  licenselint:
    uses: diggsweden/.github/.github/workflows/license-lint.yml@main
  misclint:
    permissions:
      contents: read
      security-events: write
    uses: diggsweden/.github/.github/workflows/megalint.yml@main
  test:
    permissions:
      contents: read
    if: always()
    needs: [commitlint, dependencyreviewlint, misclint]
    uses: ./.github/workflows/test.yml
